[project]
name = "t-tests-and-anova"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyterlab>=4.4.3",
    "numpy>=2.2.6",
    "scikit-learn>=1.7.0",
]
